version: 2
updates:
  - package-ecosystem: gomod
    directory: /docs/modules/ROOT/examples/operator-wan/go
    target-branch: master
    schedule:
      interval: weekly
      day: monday
  - package-ecosystem: maven
    directory: /docs/modules/ROOT/examples/operator-wan/java
    target-branch: master
    schedule:
      interval: weekly
      day: monday
  - package-ecosystem: npm
    directory: /docs/modules/ROOT/examples/operator-wan/nodejs
    target-branch: master
    schedule:
      interval: weekly
      day: monday
  - package-ecosystem: github-actions
    directory: /
    target-branch: master
    schedule:
      interval: weekly
      day: monday
