= Replicate Data between Two Hazelcast Clusters with Hazelcast Platform Operator 
:page-layout: tutorial
:page-product: operator
:page-categories: Cloud Native
:page-enterprise: true
:page-est-time: 10 mins
:page-lang: go, java, node, python
:description: Learn how to keep data in sync across two Hazelcast clusters.

{description}

== Context
In this tutorial, you'll do the following:

- Deploy two Hazelcast clusters.

- Create two Hazelcast map configurations on one of the clusters.

- Synchronize map data between the two Hazelcast clusters.

== Before you Begin

Before starting this tutorial, make sure that you have the following:

* A running https://kubernetes.io/[Kubernetes] cluster
* The Kubernetes command-line tool, https://kubernetes.io/docs/tasks/tools/#kubectl[kubectl]
* A deployed xref:operator:ROOT:index.adoc[Hazelcast Platform Operator]

== Step 1. Start the Hazelcast Cluster

. Create a secret with your link:http://trialrequest.hazelcast.com/[Hazelcast Enterprise License].
+
[source, shell]
----
kubectl create secret generic hazelcast-license-key --from-literal=license-key=<hz-license-key>
----

. Create the Hazelcast clusters.
.. Run the following command to create the first cluster.
+
[source, shell]
----
cat <<EOF | kubectl apply -f -
apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: hazelcast-first
spec:
  licenseKeySecret: hazelcast-license-key
  exposeExternally:
    type: Unisocket
    discoveryServiceType: LoadBalancer
EOF
----

.. Run the following command to create the second cluster.
+
[source, shell]
----
cat <<EOF | kubectl apply -f -
apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: hazelcast-second
spec:
  licenseKeySecret: hazelcast-license-key
  exposeExternally:
    type: Unisocket
    discoveryServiceType: LoadBalancer
EOF
----
+

. Check the status of the clusters to make sure that both clusters are running.
+
[source, shell]
----
kubectl get hazelcast
----
+
[source,shell]
----
NAME               STATUS    MEMBERS   EXTERNAL-ADDRESSES
hazelcast-first    Running   3/3       34.28.19.176:5701,34.28.19.176:5702,34.28.19.176:8081,34.28.19.176:5710
hazelcast-second   Running   3/3       35.224.41.200:5701,35.224.41.200:5702,35.224.41.200:8081,35.224.41.200:5710
----

. Find the addresses of the clusters.

+
[source, shell]
----
kubectl get service hazelcast-first hazelcast-second
----
+
[source,shell]
----
NAME               TYPE           CLUSTER-IP     EXTERNAL-IP    PORT(S)          AGE
hazelcast-first    LoadBalancer   10.96.229.87   172.18.0.222   5701:30282/TCP,5702:31120/TCP,8081:30985/TCP,5710:30009/TCP   1m
hazelcast-second   LoadBalancer   10.96.34.62    172.18.0.207   5701:31233/TCP,5702:31065/TCP,8081:30897/TCP,5710:31353/TCP   1m
----
+
The field `EXTERNAL-IP` is the address of your Hazelcast cluster.

== Step 2. Create a WAN Replication Configuration

. Create two maps on the first cluster. In this example, the following maps are created:

- `map-1`
- `map-2`.
+
[source, shell]
----
cat <<EOF | kubectl apply -f -
apiVersion: hazelcast.com/v1alpha1
kind: Map
metadata:
  name: map-1
spec:
  hazelcastResourceName: hazelcast-first
---
apiVersion: hazelcast.com/v1alpha1
kind: Map
metadata:
  name: map-2
spec:
  hazelcastResourceName: hazelcast-first
EOF
----

. Create the configuration for WAN replication:

+
- Use the first cluster as the source cluster by adding its name as a resource in the WAN Replication configuration.
Adding the cluster name as a resource starts WAN replication for both the maps that you created earlier.
+
- Add the second cluster as the target cluster to receive the WAN Replication events.

+
Run the following command to apply the configuration.

+
[source, shell]
----
cat <<EOF | kubectl apply -f -
apiVersion: hazelcast.com/v1alpha1
kind: WanReplication
metadata:
  name: wan-replication
spec:
  resources:
    - name: hazelcast-first
      kind: Hazelcast
  targetClusterName: dev
  endpoints: "<SECOND-CLUSTER-EXTERNAL-IP>"
EOF
----

. [[configure-client]]Configure the Hazelcast client to connect to the first cluster, using its address.
+
[tabs]
====

Java::
+
--
[source, java]
----
ClientConfig config = new ClientConfig();
config.getNetworkConfig().addAddress("<FIRST-CLUSTER-EXTERNAL-IP>");
----
--

NodeJS::
+
--
[source, javascript]
----
const { Client } = require('hazelcast-client');

const clientConfig = {
    network: {
        clusterMembers: [
            '<FIRST-CLUSTER-EXTERNAL-IP>'
        ]
    }
};
const client = await Client.newHazelcastClient(clientConfig);
----
--

Go::
+
--
[source, go]
----
import (
	"log"

	"github.com/hazelcast/hazelcast-go-client"
)

func main() {
	config := hazelcast.Config{}
	cc := &config.Cluster
	cc.Network.SetAddresses("<FIRST-CLUSTER-EXTERNAL-IP>")
	ctx := context.TODO()
	client, err := hazelcast.StartNewClientWithConfig(ctx, config)
	if err != nil {
		panic(err)
	}
}
----
--

Python::
+
--
[source, python]
----
import logging
import hazelcast

logging.basicConfig(level=logging.INFO)

client = hazelcast.HazelcastClient(
    cluster_members=["<FIRST-CLUSTER-EXTERNAL-IP>"],
    use_public_ip=True,
)
----
--

====
. Now start the application for each map, using the map name as an argument to fill each map with random entries. If you're reusing the sample code from this tutorial, use the map names `map-1` and `map-2`.
+

+
[tabs]
====

Java::
+
--
[source, bash]
----
cd clients/java
mvn package
java -jar target/*jar-with-dependencies*.jar fill <MAP-NAME>
----
--

NodeJS::
+
--
[source, bash]
----
cd clients/nodejs
npm install
npm start fill <MAP-NAME>
----
--

Go::
+
--
[source, bash]
----
cd clients/go
go run main.go fill <MAP-NAME>
----
--

Python::
+
--
[source, bash]
----
cd clients/python
pip install -r requirements.txt
python main.py fill <MAP-NAME>
----
--

====
+
You should see the following output.
+
[source, shell]
----
Successful connection!
Starting to fill the map (<MAP-NAME>) with random entries.
Current map size: 2
Current map size: 3
Current map size: 4
Current map size: 5
Current map size: 6
Current map size: 7
Current map size: 8
Current map size: 9
Current map size: 10
----

== Step 3. Verify the Replication of Map Entries

In this step, you'll check the sizes of the maps on the second, target cluster to make sure that WAN replication events have been received.

. Configure the Hazelcast client to connect to the second cluster, as you did in <<configure-client, Configure the Hazelcast Client>>.
+
[tabs]
====

Java::
+
--
[source, java]
----
ClientConfig config = new ClientConfig();
config.getNetworkConfig().addAddress("<SECOND-CLUSTER-EXTERNAL-IP>");
----
--

NodeJS::
+
--
[source, javascript]
----
const { Client } = require('hazelcast-client');

const clientConfig = {
    network: {
        clusterMembers: [
            '<SECOND-CLUSTER-EXTERNAL-IP>'
        ]
    }
};
const client = await Client.newHazelcastClient(clientConfig);
----
--

Go::
+
--
[source, go]
----
import (
	"log"

	"github.com/hazelcast/hazelcast-go-client"
)

func main() {
	config := hazelcast.Config{}
	cc := &config.Cluster
	cc.Network.SetAddresses("<SECOND-CLUSTER-EXTERNAL-IP>")
	ctx := context.TODO()
	client, err := hazelcast.StartNewClientWithConfig(ctx, config)
	if err != nil {
		panic(err)
	}
}
----
--

Python::
+
--
[source, python]
----
import logging
import hazelcast

logging.basicConfig(level=logging.INFO)

client = hazelcast.HazelcastClient(
    cluster_members=["<SECOND-CLUSTER-EXTERNAL-IP>"],
    use_public_ip=True,
)
----
--
====
. Start the application for each map, using the map name as an argument to check the map size, and to check that WAN replication was successful. If you're reusing the sample code from this tutorial, use the map names `map-1` and `map-2`.
+

+
[tabs]
====

Java::
+
--
[source, bash]
----
cd clients/java
mvn package
java -jar target/*jar-with-dependencies*.jar size <MAP-NAME>
----
--

NodeJS::
+
--
[source, bash]
----
cd clients/nodejs
npm install
npm start size <MAP-NAME>
----
--

Go::
+
--
[source, bash]
----
cd clients/go
go run main.go size <MAP-NAME>
----
--

Python::
+
--
[source, bash]
----
cd clients/python
pip install -r requirements.txt
python main.py size <MAP-NAME>
----
--

====
+
You should see the following output:
+
[source, shell]
----
Successful connection!
Current map (<MAP-NAME>) size: 12
----

== Clean Up

To remove all custom resources, run the following commands:

[source, shell]
----
kubectl delete secret hazelcast-license-key
kubectl delete $(kubectl get wanreplications,map,hazelcast -o name)
----

== See Also

- xref:operator:ROOT:wan-replication.adoc[]
- xref:hazelcast-platform-operator-expose-externally.adoc[]
